server:
    port: 8080
    tomcat:
      max-threads: 40


spring.h2.console.enabled: true
spring.h2.console.path: /h2_console
spring.datasource.url: jdbc:h2:file:~/h2/testdb
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

secret.jwt : 123456789